### ISSUE TITLE
Assignment 1 Grades

### ISSUE THREAD

**Issue by IbrahimShanqiti** [dilevin/computer-graphics-csc317#73]
Hi! Sorry if I'm missing something but I haven't been able to see my A1 grades but the slides said they were already out. Are they supposed to be on markus? Thanks :)

**Comment by jennicao** [comment]
That lecture 4 slide is from last year. The actual one hasn’t been uploaded yet. But during class, the slides said that marks weren’t out yet. I don’t remember when they said it will be out though.

**Comment by IbrahimShanqiti** [comment]
Thank u so much :)
