### ISSUE TITLE
In Class Test

### ISSUE THREAD

**Issue by Pxli9130** [dilevin/computer-graphics-csc317#93]
hi, for the In Class Test in 12.03, do we have get over 40% or 50% in the In Class Test to pass the course?

**Comment by zengzix2** [comment]
Wait, if it is going to be In-Class, shouldn't it be on Dec 02?

**Comment by jennicao** [comment]
@zengzix2 see #65 for why it is Dec 3 and not 2

**Comment by zengzix2** [comment]
Oh, yeah. That makes so much sense. Thank you~

**Comment by colewiltse** [comment]
Just want to confirm, there is no autofail if we do poorly on the final test, right? I haven't seen it mentioned anywhere so I assume this isn't the case, but I would also like to make sure

**Comment by dilevin** [comment]
no autofail
